# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_e78525_idx',
            old_name='notif_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_3f8c44_idx',
            old_name='notif_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_8a8a78_idx',
            old_name='notif_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_e4c995_idx',
            old_name='notif_created_at_idx',
        ),
    ]
