# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chatmess_user_id_2ac7ef_idx',
            old_name='ai_chatmsg_user_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chatmess_user_id_3f4eea_idx',
            old_name='ai_chatmsg_user_ws_idx',
        ),
        migrations.RenameIndex(
            model_name='documentembedding',
            new_name='ai_document_documen_a703d6_idx',
            old_name='ai_docembed_doc_chunk_idx',
        ),
    ]
