# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_owner_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_owner_i_0051c7_idx',
            old_name='organizatio_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_type_c31c58_idx',
            old_name='organizatio_type_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_inn_53d0f6_idx',
            old_name='organizatio_inn_idx',
        ),
    ]
