# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_documen_6e3d29_idx',
            old_name='comments_document_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_author__25752a_idx',
            old_name='comments_author_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_parent__9f8798_idx',
            old_name='comments_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_workspa_c0958a_idx',
            old_name='documents_workspace_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_status_f31a08_idx',
            old_name='documents_status_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_uploade_aad805_idx',
            old_name='documents_uploaded_by_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_created_3c6eaa_idx',
            old_name='documents_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='documentauditlog',
            new_name='document_au_documen_6f8d8b_idx',
            old_name='audit_document_idx',
        ),
        migrations.RenameIndex(
            model_name='documentauditlog',
            new_name='document_au_user_id_fb288c_idx',
            old_name='audit_user_idx',
        ),
        migrations.RenameIndex(
            model_name='documentauditlog',
            new_name='document_au_action_43d50b_idx',
            old_name='audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='documentauditlog',
            new_name='document_au_timesta_420d3c_idx',
            old_name='audit_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='documentversion',
            new_name='document_ve_documen_c337ce_idx',
            old_name='docver_document_idx',
        ),
        migrations.RenameIndex(
            model_name='documentversion',
            new_name='document_ve_created_11bca2_idx',
            old_name='docver_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='documentversion',
            new_name='document_ve_created_c8d81d_idx',
            old_name='docver_created_at_idx',
        ),
        migrations.AlterField(
            model_name='documentauditlog',
            name='details',
            field=models.JSONField(blank=True, help_text='Дополнительные данные о действии в формате JSONB', null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='ai_diff_summary',
            field=models.JSONField(blank=True, help_text='JSONB с результатом AI-анализа изменений', null=True, verbose_name='AI: описание изменений'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='checksum',
            field=models.CharField(help_text='SHA-256 хэш файла для контроля целостности', max_length=64, verbose_name='SHA-256'),
        ),
    ]
