# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signature',
            new_name='signatures_documen_4f7eaf_idx',
            old_name='signatures_document_idx',
        ),
        migrations.RenameIndex(
            model_name='signature',
            new_name='signatures_user_id_360ef1_idx',
            old_name='signatures_user_idx',
        ),
        migrations.RenameIndex(
            model_name='signature',
            new_name='signatures_signed__2d02cc_idx',
            old_name='signatures_signed_at_idx',
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature_data',
            field=models.TextField(help_text='Base64-encoded данные рукописной подписи или КЭП', verbose_name='Данные подписи'),
        ),
    ]
