# Generated by Django 5.1.15 on 2026-04-04 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('workspaces', '0001_workspace_organization_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.SmallIntegerField(verbose_name='Год')),
                ('period_month', models.SmallIntegerField(verbose_name='Месяц (1–12)')),
                ('docs_total', models.IntegerField(default=0, verbose_name='Всего документов')),
                ('docs_completed', models.IntegerField(default=0, verbose_name='Завершённых')),
                ('docs_signed', models.IntegerField(default=0, verbose_name='Подписанных')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='Завершённых задач')),
                ('avg_completion_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Среднее время (дней)')),
                ('report_data', models.JSONField(blank=True, null=True, verbose_name='Детальные данные (JSONB)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='organizations.organization', verbose_name='Организация')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='workspaces.workspace', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Ежемесячный отчёт',
                'verbose_name_plural': 'Ежемесячные отчёты',
                'db_table': 'monthly_reports',
                'ordering': ['-period_year', '-period_month'],
                'indexes': [models.Index(fields=['organization'], name='monthly_rep_organiz_ad3586_idx'), models.Index(fields=['period_year', 'period_month'], name='monthly_rep_period__e86649_idx')],
                'unique_together': {('workspace', 'period_year', 'period_month')},
            },
        ),
    ]
