# Generated by Django 5.1.15 on 2026-04-03 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('individual', 'Индивидуальный'), ('corporate', 'Корпоративный')], max_length=20, verbose_name='Тип кабинета')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'Архивный'), ('closed', 'Закрытый')], default='active', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Рабочий кабинет',
                'verbose_name_plural': 'Рабочие кабинеты',
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('signer', 'Подписант'), ('viewer', 'Наблюдатель')], max_length=20, verbose_name='Роль')),
                ('step_order', models.IntegerField(blank=True, null=True, verbose_name='Порядок шага')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Участник кабинета',
                'verbose_name_plural': 'Участники кабинета',
                'db_table': 'workspace_members',
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['organization'], name='workspaces_organiz_d6c106_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_by'], name='workspaces_created_c5ac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['status'], name='workspaces_status_62c2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['type'], name='workspaces_type_2e589a_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace'], name='workspace_m_workspa_4a91e0_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['user'], name='workspace_m_user_id_6d97a3_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['role'], name='workspace_m_role_ce0fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['step_order'], name='workspace_m_step_or_2ad390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'user')},
        ),
    ]
