# Generated by Django 5.1.15 on 2026-04-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_workspa_d4521b_idx',
            old_name='tasks_workspace_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_documen_cd4a4e_idx',
            old_name='tasks_document_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_assigne_00feb5_idx',
            old_name='tasks_assigned_to_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_status_031d4c_idx',
            old_name='tasks_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_step_or_66253b_idx',
            old_name='tasks_step_order_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_due_dat_0359a9_idx',
            old_name='tasks_due_date_idx',
        ),
    ]
